services:
  jarvis:
    build:
      context: .
      args:
        - DEV=${DEV}
    init: true
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "3"
    # restart: always
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASS}@db/${DB_NAME}
      - SECRET=${SECRET}
      - TZ=${TZ}
      - LOG_LEVEL=${LOG_LEVEL}
      - DEV=${DEV}
      - TELEGRAM_BOTS=${TELEGRAM_BOTS}

    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    build:
      context: ./postgres
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "3"
    # restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  adminer:
    image: adminer
    # restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "3"
    depends_on:
      - db

  proxy:
    build:
      context: ./proxy
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "3"
    # restart: always
    depends_on:
      - jarvis
    ports:
      - 8000:80
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - static:/vol/static

volumes:
  db-data:
  static:
